### ISSUE TITLE
imagePullSecrets not working

### ISSUE THREAD

**Issue by enlight3d** [arvatoaws-labs/wordpress-bedrock-helm-chart#17]
Hello, the chart seems pretty good, but when using a custom image for php-fpm requiring imagePullSecrets, it doesn't work.
Modifying cron-job.yaml by adding line 44 those lines will fix it: 
```yaml
       {{- with $.Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
        {{- end }}
```

and same for hook-jobs.yaml line 22:
```yaml
    {{- with $.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
```

**Comment by runningman84** [comment]
Can you send a pull request?

**Comment by enlight3d** [comment]
done https://github.com/arvatoaws-labs/wordpress-bedrock-helm-chart/pull/18

**Comment by runningman84** [comment]
thanks
